language: python
python: 
  - 3.6
env:
  - SCRIPT='sb test test'
install:
  - pip install -r requirements.txt
  - pip install --index-url https://test.pypi.org/simple/ "solidbyte==v0.7.6b1"
  - sb accounts create -p asdf1234
  - echo "Account $(sb accounts list 2> /dev/null | egrep -o '(0x[A-Fa-f0-9]+)')"
  - ls -lah ~/.ethereum/keystore
  - sb accounts list
  - sb accounts default -a $(sb accounts list 2> /dev/null | egrep -o '(0x[A-Fa-f0-9]+)')
jobs:  
  include:
    - stage: "test-lint"
      matrix:
        include:
          - python: 3.6
      env: 
        - SCRIPT="flake8 --config .flake8"

script: $SCRIPT
